### ISSUE TITLE
Hiding large changesets

### ISSUE THREAD

**Issue by deevroman** [K-Sakanoshita/Easy_Changeset_Viewer#1]
It is very common to have changesets covering the entire planet, which interferes with viewing small changesets. It would be convenient to hide them.

-- 
Your tool is similar to https://resultmaps.neis-one.org/osm-changesets but it is open and shows information about changesets. Thank you!

**Comment by K-Sakanoshita** [comment]
Thank you for the issues.
Added ability to hide changesets for selected users.

**Comment by K-Sakanoshita** [comment]
We also added the ability to hide changesets with a large scope (since it would be a hassle to hide them every time).
