### ISSUE TITLE
The site is broken

### ISSUE THREAD

**Issue by deevroman** [K-Sakanoshita/Easy_Changeset_Viewer#3]
<img width="1207" alt="Снимок экрана 2023-09-18 в 15 31 37" src="https://github.com/K-Sakanoshita/Easy_Changeset_Viewer/assets/25708359/1a5dab81-aa17-4ebd-89cc-e8c5fa807950">

Firefox 118. Chrome 117

**Comment by K-Sakanoshita** [comment]
Sorry! and Thanks!
fixed
